[package]
name = "hello"
version = "0.1.0"
authors = ["Tomoatsu Shimada <shimada@walbrix.com>"]

[dependencies]
docopt = "0.7.0"
rand = "0.3"
sdl = "0.3.6"

[dependencies.cpython]
version = "0.1"
default-features = false
features = ["python27-sys"]
